[package]
name = "planet"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { git = "https://github.com/unitn-ap-2025/common.git", branch = "main" }
log = "0.4.28"
crossbeam-channel = "0.5.15"
lazy_static = "1.5.0"
